## Sequential NLP Project
###Digital content and entertainment industry

In [53]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [54]:
import os 
os.chdir('/content/drive/MyDrive/Colab Notebooks')

In [55]:
from keras.models import Sequential
from keras.layers import Dense, GRU, Embedding,LSTM
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.datasets import imdb

(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words = 10000)

In [56]:

print("Train size: ", len(X_train))
print("Test size:  ", len(X_test))


Train size:  25000
Test size:   25000


In [57]:
print("X_train Shape ", X_train.shape)
print("y_train Shape ", y_train.shape)

print("X_test shape ", X_test.shape)
print("y_test shape  ", y_test.shape)

print("Maximum value of a word index ")
print(max([max(sequence) for sequence in X_train]))
print("Maximum length num words of review in train ")
print(max([len(sequence) for sequence in X_train]))

X_train Shape  (25000,)
y_train Shape  (25000,)
X_test shape  (25000,)
y_test shape   (25000,)
Maximum value of a word index 
9999
Maximum length num words of review in train 
2494


In [58]:
X_train[10]

[1,
 785,
 189,
 438,
 47,
 110,
 142,
 7,
 6,
 7475,
 120,
 4,
 236,
 378,
 7,
 153,
 19,
 87,
 108,
 141,
 17,
 1004,
 5,
 2,
 883,
 2,
 23,
 8,
 4,
 136,
 2,
 2,
 4,
 7475,
 43,
 1076,
 21,
 1407,
 419,
 5,
 5202,
 120,
 91,
 682,
 189,
 2818,
 5,
 9,
 1348,
 31,
 7,
 4,
 118,
 785,
 189,
 108,
 126,
 93,
 2,
 16,
 540,
 324,
 23,
 6,
 364,
 352,
 21,
 14,
 9,
 93,
 56,
 18,
 11,
 230,
 53,
 771,
 74,
 31,
 34,
 4,
 2834,
 7,
 4,
 22,
 5,
 14,
 11,
 471,
 9,
 2,
 34,
 4,
 321,
 487,
 5,
 116,
 15,
 6584,
 4,
 22,
 9,
 6,
 2286,
 4,
 114,
 2679,
 23,
 107,
 293,
 1008,
 1172,
 5,
 328,
 1236,
 4,
 1375,
 109,
 9,
 6,
 132,
 773,
 2,
 1412,
 8,
 1172,
 18,
 7865,
 29,
 9,
 276,
 11,
 6,
 2768,
 19,
 289,
 409,
 4,
 5341,
 2140,
 2,
 648,
 1430,
 2,
 8914,
 5,
 27,
 3000,
 1432,
 7130,
 103,
 6,
 346,
 137,
 11,
 4,
 2768,
 295,
 36,
 7740,
 725,
 6,
 3208,
 273,
 11,
 4,
 1513,
 15,
 1367,
 35,
 154,
 2,
 103,
 2,
 173,
 7,
 12,
 36,
 515,
 3547,
 94,
 2547,
 1722,
 5,
 3547,
 36,
 20

In [59]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

#### Decode the feature value to get original sentence

In [60]:
# See an actual review in words

word_index = imdb.get_word_index()

reverse_word_index = dict(
[(value, key) for (key, value) in word_index.items()])

decoded_review = ' '.join(
[reverse_word_index.get(i - 3, '?') for i in X_train[10]])

print(decoded_review)

? french horror cinema has seen something of a revival over the last couple of years with great films such as inside and ? romance ? on to the scene ? ? the revival just slightly but stands head and shoulders over most modern horror titles and is surely one of the best french horror films ever made ? was obviously shot on a low budget but this is made up for in far more ways than one by the originality of the film and this in turn is ? by the excellent writing and acting that ensure the film is a winner the plot focuses on two main ideas prison and black magic the central character is a man named ? sent to prison for fraud he is put in a cell with three others the quietly insane ? body building ? marcus and his retarded boyfriend daisy after a short while in the cell together they stumble upon a hiding place in the wall that contains an old ? after ? part of it they soon realise its magical powers and realise they may be able to use it to break through the prison walls br br black magi

Now use the dictionary to get the original words from the encodings, for a particular sentence

In [61]:
for encoding in X_train[10]:
  for key, value in word_index.items():
    if encoding == value:
      print(key, end = " ")

the clear fact entertaining there life back br is safely show of performance stars br actors film him many should movie reasons to and reading and are in of scenes and and of safely out compared not boss yes to sentiment show its disappointed fact raw to it justice by br of where clear fact many your way and with city nice are is along wrong not as it way she but this anything up haven't been by who of choices br of you to as this i'd it and who of shot you'll to love for updated of you it is sequels of little quest are seen watched front chemistry to simply alive of chris being it is say easy and cry in chemistry but voodoo all it maybe this is wing film job live of objects relief and level names and dunne to be stops serial 1948 watch is men go this of wing american from russo moving is accepted put this of jerry for places so work and watch and lot br that from sometimes wondered make department introduced to wondered from action at turns in low that in gay i'm of chemistry bible i 

In [62]:
y_train[10]

1

In [63]:
X_train = pad_sequences(X_train, maxlen = 500)
X_test =  pad_sequences(X_test, maxlen = 500)

In [64]:
X_train.shape, X_test.shape

((25000, 500), (25000, 500))

In [65]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Flatten, Dense, TimeDistributed

model = Sequential()
model.add(Embedding(input_dim = 10000, output_dim = 100, input_length = 500))
model.add(LSTM(64,  return_sequences=True))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [66]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 500, 100)          1000000   
                                                                 
 lstm_2 (LSTM)               (None, 500, 64)           42240     
                                                                 
 flatten_3 (Flatten)         (None, 32000)             0         
                                                                 
 dense_7 (Dense)             (None, 512)               16384512  
                                                                 
 dense_8 (Dense)             (None, 256)               131328    
                                                                 
 dense_9 (Dense)             (None, 1)                 257       
                                                                 
Total params: 17,558,337
Trainable params: 17,558,337


In [67]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

### Fit the model (2 Marks)

In [68]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=64)

Epoch 1/10
391/391 [==============================] - 45s 110ms/step - loss: 0.3476 - accuracy: 0.8414 - val_loss: 0.3034 - val_accuracy: 0.8743
Epoch 2/10
391/391 [==============================] - 42s 106ms/step - loss: 0.1665 - accuracy: 0.9363 - val_loss: 0.3800 - val_accuracy: 0.8662
Epoch 3/10
391/391 [==============================] - 41s 106ms/step - loss: 0.0569 - accuracy: 0.9804 - val_loss: 0.4805 - val_accuracy: 0.8658
Epoch 4/10
391/391 [==============================] - 41s 106ms/step - loss: 0.0232 - accuracy: 0.9924 - val_loss: 0.6370 - val_accuracy: 0.8669
Epoch 5/10
391/391 [==============================] - 42s 106ms/step - loss: 0.0204 - accuracy: 0.9923 - val_loss: 0.7085 - val_accuracy: 0.8636
Epoch 6/10
391/391 [==============================] - 41s 105ms/step - loss: 0.0135 - accuracy: 0.9956 - val_loss: 0.8638 - val_accuracy: 0.8487
Epoch 7/10
391/391 [==============================] - 42s 106ms/step - loss: 0.0114 - accuracy: 0.9964 - val_loss: 0.7710 - val_ac

In [69]:
acc_score = model.evaluate(X_test, y_test)
print(" Accuracy %:{}".format( acc_score[1]*100))
print("Loss: {}".format(acc_score[0]))

782/782 [==============================] - 28s 35ms/step - loss: 0.8989 - accuracy: 0.8677
 Accuracy %:86.7680013179779
Loss: 0.8989366292953491


In [71]:
#Prediction
y_pred = model.predict(X_test[0].reshape((1, 500)))
y_pred

array([[0.90296924]], dtype=float32)

In [72]:
# CNN for the IMDB 
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
...
# create the model
model_CNN = Sequential()
model_CNN.add(Embedding(64, 32, input_length=500))
model_CNN.add(Conv1D(filters=32, kernel_size=3, padding='same', activation='relu'))
model_CNN.add(MaxPooling1D(pool_size=2))
model_CNN.add(Flatten())
model_CNN.add(Dense(250, activation='relu'))
model_CNN.add(Dense(1, activation='sigmoid'))
model_CNN.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model_CNN.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 500, 32)           2048      
                                                                 
 conv1d_1 (Conv1D)           (None, 500, 32)           3104      
                                                                 
 max_pooling1d_1 (MaxPooling  (None, 250, 32)          0         
 1D)                                                             
                                                                 
 flatten_4 (Flatten)         (None, 8000)              0         
                                                                 
 dense_10 (Dense)            (None, 250)               2000250   
                                                                 
 dense_11 (Dense)            (None, 1)                 251       
                                                      

In [73]:
model_CNN.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=64)

Epoch 1/10
391/391 [==============================] - 6s 13ms/step - loss: 0.6403 - accuracy: 0.6181 - val_loss: 0.6120 - val_accuracy: 0.6633
Epoch 2/10
391/391 [==============================] - 5s 12ms/step - loss: 0.5841 - accuracy: 0.6913 - val_loss: 0.6003 - val_accuracy: 0.6740
Epoch 3/10
391/391 [==============================] - 5s 12ms/step - loss: 0.5435 - accuracy: 0.7224 - val_loss: 0.5993 - val_accuracy: 0.6766
Epoch 4/10
391/391 [==============================] - 5s 12ms/step - loss: 0.4952 - accuracy: 0.7552 - val_loss: 0.6266 - val_accuracy: 0.6760
Epoch 5/10
391/391 [==============================] - 5s 12ms/step - loss: 0.4272 - accuracy: 0.7978 - val_loss: 0.6673 - val_accuracy: 0.6629
Epoch 6/10
391/391 [==============================] - 5s 12ms/step - loss: 0.3392 - accuracy: 0.8508 - val_loss: 0.7788 - val_accuracy: 0.6576
Epoch 7/10
391/391 [==============================] - 5s 12ms/step - loss: 0.2242 - accuracy: 0.9147 - val_loss: 0.9310 - val_accuracy: 0.6481

In [74]:
acc_score_CNN = model_CNN.evaluate(X_test, y_test)
print(" Accuracy %:{}".format( acc_score_CNN[1]*100))
print("Loss: {}".format(acc_score_CNN[0]))

782/782 [==============================] - 3s 4ms/step - loss: 1.8371 - accuracy: 0.6418
 Accuracy %:64.18399810791016
Loss: 1.837062954902649


In [75]:
model_CNN.predict(X_test[0].reshape((1, 500)))

array([[0.04925568]], dtype=float32)

NLP with LSTM is better model as compared to CNN.
